apiVersion: v1
kind: Secret
metadata:
  name: chartai-secrets
type: Opaque
stringData:
  firebase-api-key: "your_firebase_api_key"
  firebase-auth-domain: "your_firebase_auth_domain"
  firebase-project-id: "your_firebase_project_id"
  firebase-storage-bucket: "your_firebase_storage_bucket"
  firebase-messaging-sender-id: "your_firebase_messaging_sender_id"
  firebase-app-id: "your_firebase_app_id"
  nextauth-secret: "your_nextauth_secret"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "your-registry.com": {
          "username": "your_username",
          "password": "your_password",
          "auth": "base64_encoded_username:password"
        }
      }
    }
